# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uprofile', '0004_auto_20161205_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
