# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 21:24
from __future__ import unicode_literals

import Uprofile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uprofile', '0006_auto_20161206_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displayimage',
            name='image',
            field=models.ImageField(blank=True, height_field='image_height', null=True, upload_to=Uprofile.models.user_directory_path, width_field='image_width'),
        ),
    ]
